In [15]:
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
import pandas as pd 
import warnings 

warnings.filterwarnings('ignore')
%matplotlib inline

In [16]:
from tensorflow.keras.preprocessing.text import one_hot

In [17]:
### sentences
sent= [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good', ]

In [18]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [19]:
### Define the vocabulary size 
voc_size = 10000

In [20]:
### One Hot Representation 
one_hot_repr= [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[5761, 6489, 9974, 8182],
 [5761, 6489, 9974, 8402],
 [5761, 2231, 9974, 3399],
 [3239, 5650, 7998, 4650, 9307],
 [3239, 5650, 7998, 4650, 4598],
 [3877, 5761, 4154, 9974, 98],
 [9706, 8722, 8432, 4650]]

In [21]:
### Word Embedding Representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5761 6489 9974 8182]
 [   0    0    0    0 5761 6489 9974 8402]
 [   0    0    0    0 5761 2231 9974 3399]
 [   0    0    0 3239 5650 7998 4650 9307]
 [   0    0    0 3239 5650 7998 4650 4598]
 [   0    0    0 3877 5761 4154 9974   98]
 [   0    0    0    0 9706 8722 8432 4650]]


In [23]:
## Feature Representation
dim = 10

In [ ]:
model = Sequential()
model.add(Embedding(
    input_dim=voc_size,
    output_dim=dim,
    input_length=sent_length
))
model.compile(
    optimizer='adam',
    loss='mse'
)

In [25]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[[ 0.01030427, -0.02575686,  0.02645454, -0.02445058,
          0.01044916,  0.03037223, -0.01075114, -0.00746154,
         -0.02940655,  0.02365856],
        [ 0.01030427, -0.02575686,  0.02645454, -0.02445058,
          0.01044916,  0.03037223, -0.01075114, -0.00746154,
         -0.02940655,  0.02365856],
        [ 0.01030427, -0.02575686,  0.02645454, -0.02445058,
          0.01044916,  0.03037223, -0.01075114, -0.00746154,
         -0.02940655,  0.02365856],
        [ 0.01030427, -0.02575686,  0.02645454, -0.02445058,
          0.01044916,  0.03037223, -0.01075114, -0.00746154,
         -0.02940655,  0.02365856],
        [ 0.0335366 , -0.03834934,  0.04252541, -0.04196199,
          0.03187566,  0.00707845,  0.00211958, -0.03229469,
          0.02442496,  0.03789257],
        [-0.03981053, -0.00308945, -0.01158164, -0.03741671,
          0.03807256,  0.01769279,  0.0457669 , -0.00800134,
          0.0398152 ,  0.02352543],
        [ 0.03682793, -0.01838528, -0.00864661, -0.0

In [ ]:
single_sentence = np.array([embedded_docs[0]])
prediction = model.predict(single_sentence)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
[[[ 0.01030427 -0.02575686  0.02645454 -0.02445058  0.01044916
    0.03037223 -0.01075114 -0.00746154 -0.02940655  0.02365856]
  [ 0.01030427 -0.02575686  0.02645454 -0.02445058  0.01044916
    0.03037223 -0.01075114 -0.00746154 -0.02940655  0.02365856]
  [ 0.01030427 -0.02575686  0.02645454 -0.02445058  0.01044916
    0.03037223 -0.01075114 -0.00746154 -0.02940655  0.02365856]
  [ 0.01030427 -0.02575686  0.02645454 -0.02445058  0.01044916
    0.03037223 -0.01075114 -0.00746154 -0.02940655  0.02365856]
  [ 0.0335366  -0.03834934  0.04252541 -0.04196199  0.03187566
    0.00707845  0.00211958 -0.03229469  0.02442496  0.03789257]
  [-0.03981053 -0.00308945 -0.01158164 -0.03741671  0.03807256
    0.01769279  0.0457669  -0.00800134  0.0398152   0.02352543]
  [ 0.03682793 -0.01838528 -0.00864661 -0.034227    0.0046175
   -0.04101099  0.03175524 -0.00110719 -0.03917792  0.0337141 ]
  [ 0.00107713 -0.03856998  0.03467835 -0.04579839  0.04997441
    0.01128