In [4]:
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
import pandas as pd 
import warnings 

warnings.filterwarnings('ignore')
%matplotlib inline

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent= [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good', ]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### Define the vocabulary size 
voc_size = 10000

In [10]:
### One Hot Representation 
one_hot_repr= [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[7846, 3690, 1221, 1738],
 [7846, 3690, 1221, 4466],
 [7846, 3692, 1221, 6418],
 [7164, 7361, 1134, 989, 3327],
 [7164, 7361, 1134, 989, 3228],
 [3390, 7846, 5734, 1221, 2378],
 [7521, 8275, 4730, 989]]

In [11]:
### Word Embedding Representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7846 3690 1221 1738]
 [   0    0    0    0 7846 3690 1221 4466]
 [   0    0    0    0 7846 3692 1221 6418]
 [   0    0    0 7164 7361 1134  989 3327]
 [   0    0    0 7164 7361 1134  989 3228]
 [   0    0    0 3390 7846 5734 1221 2378]
 [   0    0    0    0 7521 8275 4730  989]]


In [15]:
## Feature Representation
dim = 10

In [16]:
model = Sequential()
model.add(Embedding(
    input_dim=voc_size,
    output_dim=dim,
    input_length=sent_length
))
model.compile(
    optimizer='adam',
    loss='mse'
)

In [ ]:
model.summary()